-- Arquivo gerado por gerar_modelo.py a partir de contrato.json e mapeamento.csv. Não edite à mão.
-- Carga da tabela fato de receita faturada corporativa a partir de BI_FP_RECEITA_FATURA_DET
-- Parâmetro: :P_MES_REF (YYYYMM)
-- Pendências do contrato:
--   - Nome da tabela destino: o documento diz apenas 'TABELA FATO'; usei DWOPR.TB_FATO_RECEITA_FATURADA.
--   - Campos VAL_ALIQUOTA_*, VAL_BASE_* e VAL_TARIFADO_* estão com 'regra de agregação a definir'; o modelo carrega o valor linha a linha, sem agregar.
--   - DW_CSP aparece como CHAR(2) na BI_DIM_CSP (item 6) e NUMBER na BI_FP_RECEITA_FATURA_DET (item 27); o modelo usa o da fatura (NUMBER).
--   - O join 5 (DW_CSP) não traz a condição; assumi igualdade.
--   - O item 64 liga BL_OFFER_GROUPS a RECEITA_FATURADA_POS.COD_OFERTA, mas a regra 13 e o item 55 ligam via BI_DIM_OFERTA_POS.COD_OFERTA; o modelo segue a regra 13.
--   - O filtro IND_CORPORATIVO = 'S' da BI_DIM_CLIENTE ficou na condição do LEFT JOIN para não descartar linhas da fatura; o filtro da extração é o da própria BI_FP_RECEITA_FATURA_DET.
--   - BL_OFFER_GROUPS fica na base TAOL1_RPT; o modelo acessa via database link TAOL1_RPT (ajuste o nome do dblink se for outro).

-- 1. Estrutura da tabela destino (executar uma vez)
CREATE TABLE DWOPR.TB_FATO_RECEITA_FATURADA (
    COD_CHARGE_CODE                VARCHAR2(15),
    DSC_CHARGE_CODE                VARCHAR2(100),
    NUM_CONTA_CLI                  NUMBER(9),
    COD_CSP                        CHAR(2),
    DW_CSP                         NUMBER,
    COD_OFERTA                     VARCHAR2(255),
    DSC_NOME_OFERTA                VARCHAR2(1024),
    DSC_NOME_OFERTA_DESCONTO       VARCHAR2(1024),
    DSC_GRUPO_TIPO_APARELHO        VARCHAR2(255),
    DSC_TIPO_APARELHO              VARCHAR2(255),
    DSC_TIPO_RECEITA               VARCHAR2(20),
    COD_PLATAFORMA                 VARCHAR2(5),
    COD_TIPO_ATIVIDADE             NUMBER(2),
    COD_UN_MEDIDA                  VARCHAR2(2),
    DAT_FATURA                     DATE,
    NUM_NTC                        VARCHAR2(16),
    NUM_SEQ_ASS                    NUMBER(31),
    VAL_ALIQUOTA_FUNTEL            NUMBER(5,2),
    VAL_ALIQUOTA_FUST              NUMBER(5,2),
    VAL_ALIQUOTA_ICMS              NUMBER(5,2),
    VAL_ALIQUOTA_ISS               NUMBER(5,2),
    VAL_ALIQUOTA_PIS               NUMBER(5,2),
    VAL_BASE_COFINS                NUMBER(9,2),
    VAL_BASE_FUNTEL                NUMBER(9,2),
    VAL_BASE_FUST                  NUMBER(9,2),
    VAL_BASE_ICMS                  NUMBER(9,2),
    VAL_BASE_ISS                   NUMBER(9,2),
    VAL_BASE_PIS                   NUMBER(9,2),
    VAL_TARIFADO_COFINS            NUMBER(9,2),
    VAL_TARIFADO_FUNTEL            NUMBER(9,2),
    VAL_TARIFADO_FUST              NUMBER(9,2),
    VAL_TARIFADO_ICMS              NUMBER(9,2),
    VAL_TARIFADO_ISS               NUMBER(9,2),
    VAL_TARIFADO_PIS               NUMBER(9,2),
    VAL_TARIFADO_TOTAL             NUMBER(9,2),
    VAL_RECEITA_LIQUIDA            NUMBER(9,2),
    IND_VAS                        CHAR(1),
    DUR_LIGACAO_DENTRO_FRANQUIA    NUMBER(12,2),
    DUR_LIGACAO_FORA_FRANQUIA      NUMBER,
    DUR_LIGACAO_REAL               NUMBER(12,2),
    DUR_LIGACAO_TARIFADA           NUMBER(12,2),
    DAT_MOVIMENTO                  DATE,
    DAT_CRIACAO_DW                 DATE,
    DAT_ATUALIZACAO_DW             DATE,
    DSC_NOME_CLIENTE               VARCHAR2(110),
    NUM_CNPJ                       VARCHAR2(14)
);

COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.COD_CHARGE_CODE IS 'Charge code';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.DSC_CHARGE_CODE IS 'Descrição da Charge Code';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.NUM_CONTA_CLI IS 'Código da BAN, identificador no Mobile';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.COD_CSP IS 'Código do CSP (LD_ID) da operadora de longa distância';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.DW_CSP IS 'Indica se a cobrança é de longa distância';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.COD_OFERTA IS 'Código da oferta no Mobile';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.DSC_NOME_OFERTA IS 'Descrição da oferta no Mobile';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.DSC_NOME_OFERTA_DESCONTO IS 'Descrição da oferta de desconto no Mobile';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.DSC_GRUPO_TIPO_APARELHO IS 'Descrição do grupo do aparelho extraído da base no IW';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.DSC_TIPO_APARELHO IS 'Descrição do tipo de aparelho';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.DSC_TIPO_RECEITA IS 'Tipo de receita da charge code (Recorrência, Uso ou Ocorrência)';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.COD_PLATAFORMA IS 'Código da plataforma no BI';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.COD_TIPO_ATIVIDADE IS 'Identificador da cobrança ou desconto na tabela CHARGE';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.COD_UN_MEDIDA IS 'Unidade de medida no sistema Mobile';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.DAT_FATURA IS 'Mês/ano de faturamento';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.NUM_NTC IS 'Número do terminal do cliente';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.NUM_SEQ_ASS IS 'Número do assinante no sistema origem';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.VAL_ALIQUOTA_FUNTEL IS 'Valor da alíquota do FUNTEL';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.VAL_ALIQUOTA_FUST IS 'Valor da alíquota do FUST';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.VAL_ALIQUOTA_ICMS IS 'Valor da alíquota do ICMS';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.VAL_ALIQUOTA_ISS IS 'Valor da alíquota do ISS';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.VAL_ALIQUOTA_PIS IS 'Valor da alíquota do PIS';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.VAL_BASE_COFINS IS 'Valor base do COFINS';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.VAL_BASE_FUNTEL IS 'Valor base do FUNTEL';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.VAL_BASE_FUST IS 'Valor base do FUST';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.VAL_BASE_ICMS IS 'Valor base do ICMS';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.VAL_BASE_ISS IS 'Valor base do ISS';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.VAL_BASE_PIS IS 'Valor base do PIS';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.VAL_TARIFADO_COFINS IS 'Valor do COFINS';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.VAL_TARIFADO_FUNTEL IS 'Valor do FUNTEL';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.VAL_TARIFADO_FUST IS 'Valor do FUST';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.VAL_TARIFADO_ICMS IS 'Valor do ICMS';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.VAL_TARIFADO_ISS IS 'Valor do ISS';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.VAL_TARIFADO_PIS IS 'Valor do PIS';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.VAL_TARIFADO_TOTAL IS 'Valor da receita bruta';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.VAL_RECEITA_LIQUIDA IS 'Valor da receita líquida';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.IND_VAS IS 'Indicador se a oferta possui SVA';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.DUR_LIGACAO_DENTRO_FRANQUIA IS 'Quantidade consumida dentro da franquia';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.DUR_LIGACAO_FORA_FRANQUIA IS 'Quantidade de evento consumido fora da franquia';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.DUR_LIGACAO_REAL IS 'Quantidade consumida';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.DUR_LIGACAO_TARIFADA IS 'Quantidade de eventos consumidos';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.DAT_MOVIMENTO IS 'Data do movimento da carga';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.DAT_CRIACAO_DW IS 'Data e hora de inclusão do registro no DW';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.DAT_ATUALIZACAO_DW IS 'Data e hora de atualização do registro no DW';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.DSC_NOME_CLIENTE IS 'Nome completo do cliente';
COMMENT ON COLUMN DWOPR.TB_FATO_RECEITA_FATURADA.NUM_CNPJ IS 'CNPJ para clientes corporativos';

-- 2. Carga mensal
DELETE FROM DWOPR.TB_FATO_RECEITA_FATURADA
 WHERE DAT_FATURA >= TO_DATE(:P_MES_REF, 'YYYYMM')
   AND DAT_FATURA < ADD_MONTHS(TO_DATE(:P_MES_REF, 'YYYYMM'), 1);

INSERT /*+ APPEND */ INTO DWOPR.TB_FATO_RECEITA_FATURADA (
    COD_CHARGE_CODE,
    DSC_CHARGE_CODE,
    NUM_CONTA_CLI,
    COD_CSP,
    DW_CSP,
    COD_OFERTA,
    DSC_NOME_OFERTA,
    DSC_NOME_OFERTA_DESCONTO,
    DSC_GRUPO_TIPO_APARELHO,
    DSC_TIPO_APARELHO,
    DSC_TIPO_RECEITA,
    COD_PLATAFORMA,
    COD_TIPO_ATIVIDADE,
    COD_UN_MEDIDA,
    DAT_FATURA,
    NUM_NTC,
    NUM_SEQ_ASS,
    VAL_ALIQUOTA_FUNTEL,
    VAL_ALIQUOTA_FUST,
    VAL_ALIQUOTA_ICMS,
    VAL_ALIQUOTA_ISS,
    VAL_ALIQUOTA_PIS,
    VAL_BASE_COFINS,
    VAL_BASE_FUNTEL,
    VAL_BASE_FUST,
    VAL_BASE_ICMS,
    VAL_BASE_ISS,
    VAL_BASE_PIS,
    VAL_TARIFADO_COFINS,
    VAL_TARIFADO_FUNTEL,
    VAL_TARIFADO_FUST,
    VAL_TARIFADO_ICMS,
    VAL_TARIFADO_ISS,
    VAL_TARIFADO_PIS,
    VAL_TARIFADO_TOTAL,
    VAL_RECEITA_LIQUIDA,
    IND_VAS,
    DUR_LIGACAO_DENTRO_FRANQUIA,
    DUR_LIGACAO_FORA_FRANQUIA,
    DUR_LIGACAO_REAL,
    DUR_LIGACAO_TARIFADA,
    DAT_MOVIMENTO,
    DAT_CRIACAO_DW,
    DAT_ATUALIZACAO_DW,
    DSC_NOME_CLIENTE,
    NUM_CNPJ
)
WITH BASE AS (
    SELECT
           CC.COD_CHARGE_CODE                       AS COD_CHARGE_CODE,
           CC.DSC_CHARGE_CODE                       AS DSC_CHARGE_CODE,
           RFD.NUM_CONTA_CLI                        AS NUM_CONTA_CLI,
           CSP.COD_CSP                              AS COD_CSP,
           RFD.DW_CSP                               AS DW_CSP,
           OFE.COD_OFERTA                           AS COD_OFERTA,
           OFE.DSC_NOME_OFERTA                      AS DSC_NOME_OFERTA,
           OFD.DSC_NOME_OFERTA                      AS DSC_NOME_OFERTA_DESCONTO,
           TA.DSC_GRUPO_TIPO_APARELHO               AS DSC_GRUPO_TIPO_APARELHO,
           TA.DSC_TIPO_APARELHO                     AS DSC_TIPO_APARELHO,
           TR.DSC_TIPO_RECEITA                      AS DSC_TIPO_RECEITA,
           RFD.COD_PLATAFORMA                       AS COD_PLATAFORMA,
           RFD.COD_TIPO_ATIVIDADE                   AS COD_TIPO_ATIVIDADE,
           RFD.COD_UN_MEDIDA                        AS COD_UN_MEDIDA,
           RFD.DAT_FATURA                           AS DAT_FATURA,
           RFD.NUM_NTC                              AS NUM_NTC,
           RFD.NUM_SEQ_ASS                          AS NUM_SEQ_ASS,
           RFD.VAL_ALIQUOTA_FUNTEL                  AS VAL_ALIQUOTA_FUNTEL,
           RFD.VAL_ALIQUOTA_FUST                    AS VAL_ALIQUOTA_FUST,
           RFD.VAL_ALIQUOTA_ICMS                    AS VAL_ALIQUOTA_ICMS,
           RFD.VAL_ALIQUOTA_ISS                     AS VAL_ALIQUOTA_ISS,
           RFD.VAL_ALIQUOTA_PIS                     AS VAL_ALIQUOTA_PIS,
           RFD.VAL_BASE_COFINS                      AS VAL_BASE_COFINS,
           RFD.VAL_BASE_FUNTEL                      AS VAL_BASE_FUNTEL,
           RFD.VAL_BASE_FUST                        AS VAL_BASE_FUST,
           RFD.VAL_BASE_ICMS                        AS VAL_BASE_ICMS,
           RFD.VAL_BASE_ISS                         AS VAL_BASE_ISS,
           RFD.VAL_BASE_PIS                         AS VAL_BASE_PIS,
           RFD.VAL_TARIFADO_COFINS                  AS VAL_TARIFADO_COFINS,
           RFD.VAL_TARIFADO_FUNTEL                  AS VAL_TARIFADO_FUNTEL,
           RFD.VAL_TARIFADO_FUST                    AS VAL_TARIFADO_FUST,
           RFD.VAL_TARIFADO_ICMS                    AS VAL_TARIFADO_ICMS,
           RFD.VAL_TARIFADO_ISS                     AS VAL_TARIFADO_ISS,
           RFD.VAL_TARIFADO_PIS                     AS VAL_TARIFADO_PIS,
           RFD.VAL_TARIFADO_TOTAL                   AS VAL_TARIFADO_TOTAL,
           NVL(RFD.VAL_TARIFADO_TOTAL,0) - (NVL(RFD.VAL_TARIFADO_ICMS,0) + NVL(RFD.VAL_TARIFADO_ISS,0) + NVL(RFD.VAL_TARIFADO_COFINS,0) + NVL(RFD.VAL_TARIFADO_PIS,0)) AS VAL_RECEITA_LIQUIDA,
           CASE WHEN BOG.OFFER_GROUP = 'PCT_SVA' THEN 'S' ELSE 'N' END AS IND_VAS,
           POS.DUR_LIGACAO_DENTRO_FRANQUIA          AS DUR_LIGACAO_DENTRO_FRANQUIA,
           POS.DUR_LIGACAO_FORA_FRANQUIA            AS DUR_LIGACAO_FORA_FRANQUIA,
           POS.DUR_LIGACAO_REAL                     AS DUR_LIGACAO_REAL,
           POS.DUR_LIGACAO_TARIFADA                 AS DUR_LIGACAO_TARIFADA,
           RFD.DAT_FATURA                           AS DAT_MOVIMENTO,
           SYSDATE                                  AS DAT_CRIACAO_DW,
           SYSDATE                                  AS DAT_ATUALIZACAO_DW,
           CLI.DSC_NOME_CLIENTE                     AS DSC_NOME_CLIENTE,
           CLI.NUM_CNPJ                             AS NUM_CNPJ,
           ROW_NUMBER() OVER (PARTITION BY RFD.ROWID ORDER BY AM.DAT_REFERENCIA DESC, AM.DAT_ULT_CHAMADA DESC NULLS LAST, AM.DW_TIPO_APARELHO) AS RN_AM
      FROM DWH.BI_FP_RECEITA_FATURA_DET RFD
  -- regra 1: BI_FP_RECEITA_FATURADA_POS
  LEFT JOIN (
        SELECT COD_ASSINANTE,
               DAT_FATURAMENTO,
               DW_NUM_CONTA_CLI,
               DW_CHARGE_CODE,
               SUM(DUR_LIGACAO_DENTRO_FRANQUIA) AS DUR_LIGACAO_DENTRO_FRANQUIA,
               SUM(DUR_LIGACAO_FORA_FRANQUIA) AS DUR_LIGACAO_FORA_FRANQUIA,
               SUM(DUR_LIGACAO_REAL) AS DUR_LIGACAO_REAL,
               SUM(DUR_LIGACAO_TARIFADA) AS DUR_LIGACAO_TARIFADA
          FROM DWH.BI_FP_RECEITA_FATURADA_POS
         GROUP BY COD_ASSINANTE, DAT_FATURAMENTO, DW_NUM_CONTA_CLI, DW_CHARGE_CODE
    ) POS
        ON TO_CHAR(RFD.NUM_SEQ_ASS) = POS.COD_ASSINANTE
       AND RFD.DAT_FATURA = POS.DAT_FATURAMENTO
       AND RFD.DW_NUM_CONTA_CLI = POS.DW_NUM_CONTA_CLI
       AND RFD.DW_CHARGE_CODE = POS.DW_CHARGE_CODE
  -- regra 2: BI_DIM_CHARGE_CODE
  LEFT JOIN DWH.BI_DIM_CHARGE_CODE CC
        ON RFD.DW_CHARGE_CODE = CC.DW_CHARGE_CODE
  -- regra 11: BI_DIM_TIPO_RECEITA
  LEFT JOIN DWH.BI_DIM_TIPO_RECEITA TR
        ON CC.COD_TIPO_RECEITA = TR.COD_TIPO_RECEITA
  -- regra 3: Join separado do DW_OFERTA_DESCONTO
  LEFT JOIN DWH.BI_DIM_OFERTA_POS OFE
        ON RFD.DW_OFERTA = OFE.DW_OFERTA
  -- regra 4: Join separado do DW_OFERTA, traz somente a oferta de desconto
  LEFT JOIN DWH.BI_DIM_OFERTA_POS OFD
        ON RFD.DW_OFERTA_DESCONTO = OFD.DW_OFERTA
  -- regra 13: BL_OFFER_GROUPS
  LEFT JOIN MTAAPPC.BL_OFFER_GROUPS@TAOL1_RPT BOG
        ON OFE.COD_OFERTA = TO_CHAR(BOG.OFFER)
       AND BOG.OFFER_GROUP = 'PCT_SVA'
  -- regra 5: BI_DIM_CSP
  LEFT JOIN DWH.BI_DIM_CSP CSP
        ON RFD.DW_CSP = CSP.DW_CSP
  -- regra 6: Último aparelho utilizado: maior DAT_REFERENCIA até a fatura; havendo mais de um, fica o primeiro
  LEFT JOIN DWH.BI_FP_ASS_APARELHO_MENSAL AM
        ON RFD.NUM_NTC = AM.NUM_NTC
       AND RFD.DAT_FATURA >= AM.DAT_REFERENCIA
       AND RFD.NUM_CLIENTE = AM.NUM_CLIENTE
       AND AM.IND_ULT_APARELHO_UTILIZADO = 'S'
  -- regra 12: BI_DIM_TIPO_APARELHO
  LEFT JOIN DWH.BI_DIM_TIPO_APARELHO TA
        ON AM.DW_TIPO_APARELHO = TA.DW_TIPO_APARELHO
  -- regra 8: BI_DIM_CLIENTE
  LEFT JOIN DWH.BI_DIM_CLIENTE CLI
        ON RFD.DW_NUM_CLIENTE = CLI.DW_NUM_CLIENTE
       AND CLI.IND_CORPORATIVO = 'S'
     WHERE RFD.DAT_FATURA >= TO_DATE(:P_MES_REF, 'YYYYMM')
       AND RFD.DAT_FATURA < ADD_MONTHS(TO_DATE(:P_MES_REF, 'YYYYMM'), 1)
       AND RFD.IND_CORPORATIVO = 'S'
)
SELECT COD_CHARGE_CODE,
       DSC_CHARGE_CODE,
       NUM_CONTA_CLI,
       COD_CSP,
       DW_CSP,
       COD_OFERTA,
       DSC_NOME_OFERTA,
       DSC_NOME_OFERTA_DESCONTO,
       DSC_GRUPO_TIPO_APARELHO,
       DSC_TIPO_APARELHO,
       DSC_TIPO_RECEITA,
       COD_PLATAFORMA,
       COD_TIPO_ATIVIDADE,
       COD_UN_MEDIDA,
       DAT_FATURA,
       NUM_NTC,
       NUM_SEQ_ASS,
       VAL_ALIQUOTA_FUNTEL,
       VAL_ALIQUOTA_FUST,
       VAL_ALIQUOTA_ICMS,
       VAL_ALIQUOTA_ISS,
       VAL_ALIQUOTA_PIS,
       VAL_BASE_COFINS,
       VAL_BASE_FUNTEL,
       VAL_BASE_FUST,
       VAL_BASE_ICMS,
       VAL_BASE_ISS,
       VAL_BASE_PIS,
       VAL_TARIFADO_COFINS,
       VAL_TARIFADO_FUNTEL,
       VAL_TARIFADO_FUST,
       VAL_TARIFADO_ICMS,
       VAL_TARIFADO_ISS,
       VAL_TARIFADO_PIS,
       VAL_TARIFADO_TOTAL,
       VAL_RECEITA_LIQUIDA,
       IND_VAS,
       DUR_LIGACAO_DENTRO_FRANQUIA,
       DUR_LIGACAO_FORA_FRANQUIA,
       DUR_LIGACAO_REAL,
       DUR_LIGACAO_TARIFADA,
       DAT_MOVIMENTO,
       DAT_CRIACAO_DW,
       DAT_ATUALIZACAO_DW,
       DSC_NOME_CLIENTE,
       NUM_CNPJ
  FROM BASE
 WHERE RN_AM = 1;

COMMIT;
